[package]
name = "Horse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uefi = {version="0.12", features=["alloc", "exts"]}
uefi-services = "0.9"
