[package]
name = "horse-bootloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uefi = { version = "0.18.0", features = ["exts", "alloc", "logger"] }
log = { version = "0.4.11", default-features = false }
goblin = {version = "0.4", features = ["elf32", "elf64", "endian_fd"], default-features = false}
libloader = {path = "../libloader"}
